language: java
jdk:
  - openjdk8

install: true
script:
  - mvn clean package
  - java -jar ./target/protogen-1.0-SNAPSHOT-shaded.jar all

cache:
  directories:
    - $HOME/.m2

before_deploy:
  - zip -r generated.zip gen/ gen-broken/

deploy:
  provider: releases
  api_key: $GITHUB_RELEASES_OATH_TOKEN
  file: generated.zip
  skip_cleanup: true
  on:
    tag: true
